export const FETCH_DATA = "FETCH_DATA";
export const DOW_JONES = "DOW_JONES";
export const NASDAQ = "NASDAQ";
export const SP500 = "SP500";

export const SET_WEEK_SELECTED = "SET_WEEK_SELECTED";

export const SET_SCORE_STYLE = "SET_SCORE_STYLE";

export const FETCH_TICKER = "FETCH_TICKER";

export const ADD_PORTFOLIO = "ADD_PORTFOLIO";
export const REMOVE_PORTFOLIO = "REMOVE_PORTFOLIO";

export const SET_TYPE = "SET_TYPE";

export const TOGGLE_COUNT_SIGN = "TOGGLE_COUNT_SIGN";
export const SET_EARNING_PAGE = "SET_EARNING_PAGE";
export const CHANGE_THRESHOLD = "CHANGE_THRESHOLD";

export const UNLOCKED_TICKER = "UNLOCKED_TICKER";
export const SET_PAYMENT_METHOD = "SET_PAYMENT_METHOD";

export const ADD_PORTFOLIO_LENGTH = "ADD_PORTFOLIO_LENGTH";
export const MAKE_PORTFOLIO_PAYMENT = "MAKE_PORTFOLIO_PAYMENT";

export const CLOSE_MODAL = "CLOSE_MODAL";
